apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - database-password.yaml
  - volume-mysql.yaml

namePrefix: dev-

secretGenerator:
- name: mysecrets
  literals:
  - ROOT_PASSWORD=thisisnotsecure
  type: Opaque
