apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - database-password.yaml
  - volume-mysql.yaml
  - ressource-limit.yaml

namePrefix: prod-
commonLabels:
 tier: prod
commonAnnotations:
  documentation: "https://github.com/arnnow/k8s-mysql/tree/master/kustomize"

secretGenerator:
- name: mysecrets
  literals:
  - ROOT_PASSWORD=thisisnotsecure
  type: Opaque
